## 应用服务 WEB 访问端口
#server:
#  port: 8088
spring:
  # FreeMarker 配置
  freemarker:
    suffix: .html
  # 应用名称
  application:
    name: msmp
  # MVC 配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Jackson 配置
  jackson:
    time-zone: GMT+8


# 配置日志  log-impl:日志实现
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1
      logic-not-delete-value: 0
#mapper-locations: classpath:com/yw/msmp/mapper/xml/*.xml

# 角色id
position:
  positionId:
    manager: 2
    clerk: 3
    supplier: 4
    delivery: 6

role:
  roleId:
    administrator: 1
    manager: 2
    clerk: 3
    supplier: 4
    user: 5
    delivery: 6

