@startuml

title 药物销售系统- 添加订单流程图

actor 用户 as u
participant 前端界面 as fui
participant 后台服务 as bs
database 数据库 as db

u -> fui : 进入首页并登录账号
fui -> bs : 根据用户权限查询可操作的商家信息
bs --> fui: 返回满足条件的商家列表

loop 选择合适店铺进行操作：
    fui -> bs: 选中目标商家，并请求加载该商家所包含商品数据
    bs --> fui: 提供当前所有在售产品清单及其详细规格说明

    alt 开始创建新订单:
        loop 操作员持续添加购买项直至结束:
            user->fui: 在前端增加相应数量和种类药品到结算区域 输入价格与折扣码（若有）
            activate BS #green
                group 验证是否为有效药品且数量充足:
                    BS->db:"检索相关数据库"
                    db-->BS:"返回验证结果"
                end
        end

        fui -> bs : 确认提交当前药品清单并进行下一步确认
        bs --> fui : 返回已创建的初步订单，等待操作员进一步填写信息
    else 已有未完成订单:
       fui -> bs : 请求加载上次未保存完整的购物车缓存数据（若存在）
       loop 编辑前面尚未确定属性值或者数量不够：
           user->fui: 在前端修改指定行记录中的价格和折扣码 或调整商品个数

           activate BS #green
                group 验证是否为有效药品且数量充足:
                    BS->db:"检索相关数据库"
                    db-->BS:"返回验证结果"
                end
           fui -> bs : 提交最新更改至后台服务器做校验与处理
           bs --> fui : 更新本地视图状态，让用户继续编辑或直接支付
       end
    end

end

loop 选择合适的支付方式:

    alt 微信/支付宝付款方式：
          usr->fUI: 加载微信/支付宝客户端页面二维码，并跳转到对应链接。
          UI-->usr: 显示扫码界面，并等待用户支付完成.
          activate BS #green
            group 检查是否已经付款成功：
                alt 会自动检测到状态改变:
                    BS-> db: 维护订单表，顺序更新交易记录信息
                    db-->BS: 返回确认结果。
                else 用户手动查询当前所选的订单或者联系客服人员寻求解决办法：
                 end
           deactivate BS
        else 支持银行卡网络支付方式：
         fui -> bs : 请求加载支持的银行列表和相应缩略图
         bs --> fui : 提供所有可用于此次交易进行验证操作的网关URL 和 网络参数

        usr->fUI: 加载对应网页并输入相关信息, 包括（但不限于）账号、密码及验证码。
          UI-->usr: 等待页面刷新后再继续下一步操作.

    end

end

fui -> bs : 向后台请求确认该笔交易并返回处理结果
bs --> fui : 处理完毕之后回传消息通知给前端展示

@enduml