@startuml
title 在线下单流程

|用户|
start
: 选择商品;
: 提交订单;
|后端服务器|
if (是否库存不足) then (yes)
  : 显示库存不足;
else (no)
  : 初步检查订单;
  : 进入订单确认页面;
  |用户|
  : 完善支付方式、地址等信息;
  : 提交订单;
  |后端服务器|
  if (是否库存不足) then (yes)
    : 显示库存不足;
  else (no)
    : 检查支付方式、地址等信息;
    : 减库存;
    : 新建订单;
    : 增加订单明细;
    : 返回订单信息;
    |支付宝|
    : 发起支付调用;
    |用户|
    : 支付;
    : 主动确认支付状态;
    |后端服务器|
    : 检查支付状态;
    if (支付状态正确) then (yes)
      : 正常返回选购页面;
    else (no)
      : 显示错误信息;
    endif
  endif
endif
stop
@enduml
