@startuml
left to right direction
actor 管理员
actor 用户

rectangle 药店管理系统 {
    usecase 管理菜单
    usecase 管理人员
    usecase 管理角色
    usecase 管理药品品牌
    usecase 管理药品基础资料
    usecase 管理药品详情
    usecase 管理药品品类
    usecase 管理仓库批次
    usecase 管理店铺列表
    usecase 管理店铺职员
    usecase 管理店铺职位
    usecase 管理店铺批次
    usecase 管理订单
    usecase 管理随访项
    usecase 管理随访记录
    usecase 管理在线及线下销售
    usecase 用户购买药品
    usecase 用户查看订单

    管理员 --> 管理菜单
    管理员 --> 管理人员
    管理员 --> 管理角色
    管理员 --> 管理药品品牌
    管理员 --> 管理药品基础资料
    管理员 --> 管理药品详情
    管理员 --> 管理药品品类
    管理员 --> 管理仓库批次
    管理员 --> 管理店铺列表
    管理员 --> 管理店铺职员
    管理员 --> 管理店铺职位
    管理员 --> 管理店铺批次
    管理员 --> 管理订单
    管理员 --> 管理随访项
    管理员 --> 管理随访记录
    管理员 --> 管理在线及线下销售

    用户 --> 用户购买药品
    用户 --> 用户查看订单

    用户购买药品 --> 管理在线及线下销售
    用户查看订单 --> 管理订单

    管理药品详情 --> 管理药品品牌
    管理药品详情 --> 管理药品基础资料
    管理药品详情 --> 管理药品品类

    管理仓库批次 --> 管理药品详情

    管理随访记录 --> 管理随访项
}
@enduml
