@startuml
title 调货流程

|店铺|
start
: 新建店铺批次;
|仓库|
if (是否符合要求) then (no)
  : 审核不同意;
  : 重新提交申请;
else (yes)
  : 更新店铺批次状态为正常;
  : 按从老批次到新批次的顺序调药品;
  if (批次充足) then (yes)
    : 生成配送信息;
    |物流公司|
    : 配送;
    |店铺|
    : 等待配送;
    if (配送达到) then (yes)
      : 上架;
      : 提供在线和线下两种销售方式;
    endif
  else (no)
    : 拆分店铺批次;
    : 多次申请;
  endif
endif
stop
@enduml
